# ANDROID_BUILD_VERSION=30
# ANDROID_TOOLS_VERSION=30.0.3
# NODE_VERSION=14.x
image: reactnativecommunity/react-native-android:5.1

pipelines:
  default:
    - step:
        name: Build Android
        caches:
          - node
          - gradle
        script:
          - yarn install --frozen-lockfile
          - yarn build
        artifacts:
          - android/app/build/outputs/**