require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'noveltyhrmobile' do
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  
  config = use_native_modules!
  pod 'GoogleSignIn'
  pod 'Firebase/Messaging'
  use_react_native!(:path => config["reactNativePath"])

  target 'noveltyhrmobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'noveltyhrmobile-tvOS' do
  # Pods for noveltyhrmobile-tvOS

  target 'noveltyhrmobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
